#! /bin/bash
auto_sudo () {
    echo $PASS | sudo -S $1 $2 $3 $4 $5 $6
}

cd ~/
read -sp "Input your password: " PASS
echo ""
echo "Setup starts soon..."
auto_sudo apt update
auto_sudo apt upgrade -y
echo $PASS | sudo -S apt install --fix-missing -y \
    build-essential \
    python3-dev \
    vim \
    ruby \
    ruby-dev \
    wget \
    gdb \
    git \
    python3-pip \
    default-jdk \
    texlive-full \
    evince

auto_sudo apt-get install gnuplot

curl https://osdn.net/projects/mytexpert/downloads/26068/jlisting.sty.bz2/ -o jlisting.sty.bz2 -L
bzip2 -d jlisting.sty.bz2
cd /usr/share/texlive/texmf-dist/tex/latex/listings/
auto_sudo mv ~/jlisting.sty ./
auto_sudo chmod 644 jlisting.sty
auto_sudo mktexlsr
echo "[+] install jlisting done"

auto_sudo python3 -m pip install ipython
echo "[+] pip install ipython done"

echo "[+] apt install done"